# Generated by Django 2.2 on 2020-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=10)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
