# Generated by Django 2.2 on 2020-03-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_catalogo_productos'),
        ('producto', '0004_remove_producto_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='catalogo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Catalogo'),
        ),
    ]
