# Generated by Django 2.2 on 2020-03-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('tipo', models.CharField(max_length=20)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Catalogo')),
                ('inventario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bodega.InventarioBodega')),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.FloatField(default=None, null=True)),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto')),
            ],
        ),
    ]
