# Generated by Django 2.2 on 2020-03-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_producto_productos'),
        ('catalogo', '0002_remove_catalogo_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='productos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
