# Generated by Django 2.2 on 2020-03-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioBodega',
            fields=[
                ('id', models.FloatField(default=None, primary_key=True, serialize=False)),
            ],
        ),
    ]
