# Generated by Django 3.0.6 on 2020-05-29 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.FloatField(default=None, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('cant', models.FloatField(default=None, null=True)),
                ('fechaLlegada', models.DateTimeField(auto_now_add=True)),
                ('provid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Proveedor')),
            ],
        ),
    ]
