# Generated by Django 2.2 on 2020-05-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_productoproveedor_numbodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproveedor',
            name='foto',
        ),
    ]
