# Generated by Django 3.0.6 on 2020-05-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('tipo', models.CharField(max_length=20)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura')),
            ],
        ),
    ]
